// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Main from "./Main.js";

var $$default = Main.app;

export {
  $$default ,
  $$default as default,
  
}
/* Main Not a pure module */
